import { provideHttpClient, withFetch, withInterceptors } from '@angular/common/http';
import { ApplicationConfig, importProvidersFrom, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withInMemoryScrolling } from '@angular/router';
import { provideTranslateLoader, provideTranslateService } from '@ngx-translate/core';
import {
  ArrowLeft,
  Ban,
  BarChart3,
  Bell,
  Biohazard,
  Building2,
  BookmarkPlus,
  Bug,
  Camera,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Check,
  CheckCircle2,
  Circle,
  CircleHelp,
  CircleQuestionMark,
  CircleUserRound,
  Copy,
  Crown,
  Dices,
  DoorOpen,
  Eye,
  EyeOff,
  FileDown,
  FileUp,
  Folder,
  FolderPlus,
  Flag,
  Gift,
  Globe,
  Ghost,
  History,
  Image,
  Info,
  Library,
  LayoutGrid,
  KeyRound,
  Layers3,
  List,
  Link,
  Link2Off,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  LucideAngularModule,
  MapPin,
  Maximize2,
  Menu,
  MessageSquare,
  Minus,
  MoonStar,
  MoreVertical,
  Pencil,
  Play,
  Plus,
  RefreshCcw,
  RotateCcw,
  RotateCw,
  Radiation,
  Save,
  Search,
  SearchX,
  Send,
  Settings,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  Skull,
  Sparkles,
  Swords,
  Sun,
  TabletSmartphone,
  Tickets,
  Trash,
  Trash2,
  Trophy,
  TriangleAlert,
  Upload,
  Unlink2,
  UserPlus,
  Users,
  Vote,
  X,
  Zap,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/auth/auth.interceptor';
import { loadingInterceptor } from './core/loading/loading.interceptor';
import { DEFAULT_LOCALE } from './core/localization/locale-config';
import { RuntimeTranslationLoader } from './core/localization/runtime-translation-loader';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withInMemoryScrolling({
      anchorScrolling: 'enabled',
      scrollPositionRestoration: 'top',
    })),
    provideHttpClient(withFetch(), withInterceptors([loadingInterceptor, authInterceptor])),
    provideTranslateService({
      fallbackLang: DEFAULT_LOCALE.code,
      lang: DEFAULT_LOCALE.code,
      loader: provideTranslateLoader(RuntimeTranslationLoader),
    }),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowLeft,
        Ban,
        BarChart3,
        Bell,
        Biohazard,
        Building2,
        BookmarkPlus,
        Bug,
        Camera,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        Check,
        CheckCircle2,
        Circle,
        CircleHelp,
        CircleQuestionMark,
        CircleUserRound,
        Copy,
        Crown,
        Dices,
        DoorOpen,
        Eye,
        EyeOff,
        FileDown,
        FileUp,
        Folder,
        FolderPlus,
        Flag,
        Gift,
        Globe,
        Ghost,
        History,
        Image,
        Info,
        Library,
        LayoutGrid,
        KeyRound,
        Layers3,
        List,
        Link,
        Link2Off,
        LoaderCircle,
        Lock,
        LogIn,
        LogOut,
        MapPin,
        Maximize2,
        Menu,
        MessageSquare,
        Minus,
        MoonStar,
        MoreVertical,
        Pencil,
        Play,
        Plus,
        RefreshCcw,
        RotateCcw,
        RotateCw,
        Radiation,
        Save,
        Search,
        SearchX,
        Send,
        Settings,
        ShieldCheck,
        Shuffle,
        SlidersHorizontal,
        Skull,
        Sparkles,
        Swords,
        Sun,
        TabletSmartphone,
        Tickets,
        Trash,
        Trash2,
        Trophy,
        TriangleAlert,
        Upload,
        Unlink2,
        UserPlus,
        Users,
        Vote,
        X,
        Zap,
      }),
    ),
  ]
};
