import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { ApplicationConfig, importProvidersFrom, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  ArrowLeft,
  BarChart3,
  Bell,
  Building2,
  BookmarkPlus,
  Camera,
  ChevronDown,
  ChevronRight,
  Check,
  CheckCircle2,
  CircleUserRound,
  Copy,
  DoorOpen,
  EyeOff,
  FileUp,
  Folder,
  FolderPlus,
  Globe,
  History,
  KeyRound,
  Layers3,
  Lock,
  LogIn,
  LogOut,
  LucideAngularModule,
  Menu,
  MessageSquare,
  MoreVertical,
  Pencil,
  Play,
  Plus,
  RefreshCcw,
  RotateCcw,
  RotateCw,
  Save,
  Search,
  SearchX,
  Send,
  ShieldCheck,
  Swords,
  TabletSmartphone,
  Trash,
  Trash2,
  TriangleAlert,
  Upload,
  UserPlus,
  Users,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/auth/auth.interceptor';
import { loadingInterceptor } from './core/loading/loading.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withInterceptors([loadingInterceptor, authInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({
        ArrowLeft,
        BarChart3,
        Bell,
        Building2,
        BookmarkPlus,
        Camera,
        ChevronDown,
        ChevronRight,
        Check,
        CheckCircle2,
        CircleUserRound,
        Copy,
        DoorOpen,
        EyeOff,
        FileUp,
        Folder,
        FolderPlus,
        Globe,
        History,
        KeyRound,
        Layers3,
        Lock,
        LogIn,
        LogOut,
        Menu,
        MessageSquare,
        MoreVertical,
        Pencil,
        Play,
        Plus,
        RefreshCcw,
        RotateCcw,
        RotateCw,
        Save,
        Search,
        SearchX,
        Send,
        ShieldCheck,
        Swords,
        TabletSmartphone,
        Trash,
        Trash2,
        TriangleAlert,
        Upload,
        UserPlus,
        Users,
        X,
      }),
    ),
  ]
};
