<?php

return [
    'fast_mana' => [
        'Sol Ring',
        'Mana Crypt',
        'Mana Vault',
        'Chrome Mox',
        'Mox Diamond',
        'Jeweled Lotus',
        'Lotus Petal',
        'Black Lotus',
        'Lion\'s Eye Diamond',
        'Grim Monolith',
        'Mox Amber',
    ],
    'free_interaction' => [
        'Fierce Guardianship',
        'Deflecting Swat',
        'Deadly Rollick',
        'Force of Will',
        'Force of Negation',
        'Pact of Negation',
        'Flawless Maneuver',
        'Mindbreak Trap',
        'Misdirection',
        'Commandeer',
    ],
    'efficient_tutor' => [
        'Demonic Tutor',
        'Vampiric Tutor',
        'Enlightened Tutor',
        'Mystical Tutor',
        'Worldly Tutor',
        'Imperial Seal',
        'Gamble',
        'Finale of Devastation',
        "Green Sun's Zenith",
        'Chord of Calling',
        'Demonic Consultation',
        'Tainted Pact',
        'Doomsday',
    ],
    'compact_wincon' => [
        "Thassa's Oracle",
        'Underworld Breach',
        'Aetherflux Reservoir',
        'Walking Ballista',
        'Laboratory Maniac',
        'Jace, Wielder of Mysteries',
        'Doomsday',
        'Isochron Scepter',
        'Exquisite Blood',
        'Sanguine Bond',
        'Vito, Thorn of the Dusk Rose',
        'Bloodchief Ascension',
        'Mindcrank',
    ],
    'cedh_staple' => [
        'Sol Ring',
        'Mana Crypt',
        'Demonic Tutor',
        'Rhystic Study',
        'Mystic Remora',
        'Dockside Extortionist',
        "Thassa's Oracle",
        'Underworld Breach',
    ],
    'high_power_staple' => [
        'Cyclonic Rift',
        'Smothering Tithe',
        'Esper Sentinel',
        'The One Ring',
        'Dockside Extortionist',
        'Rhystic Study',
        'Necropotence',
        'Teferi\'s Protection',
    ],
    'mana_positive_combo_piece' => [
        'Dockside Extortionist',
        'Lion\'s Eye Diamond',
        'Black Lotus',
        'Underworld Breach',
        "Jeska's Will",
        'Dramatic Reversal',
        'Isochron Scepter',
        'Basalt Monolith',
        'Rings of Brighthearth',
        'Grim Monolith',
        'Food Chain',
        'Brain Freeze',
    ],
    'low_opportunity_cost' => [
        'Malakir Rebirth',
        'Bala Ged Recovery',
        'Sejiri Shelter',
        'Agadeem\'s Awakening',
        'Emeria\'s Call',
        'Valakut Awakening',
        'Hagra Mauling',
        'Boseiju, Who Endures',
        'Otawara, Soaring City',
        'Takenuma, Abandoned Mire',
        'Eiganjo, Seat of the Empire',
        'Sokenzan, Crucible of Defiance',
        'Feed the Swarm',
        'Abrade',
        'Wear // Tear',
        'Return to Nature',
        'Assassin\'s Trophy',
        'Generous Gift',
        'Beast Within',
    ],
];
