export const CATALAN_FALSE_POSITIVE_EXPRESSIONS: ReadonlySet<string> = new Set([
  'abro',
  'abrona',
  'agat',
  'agada',
  'alparida',
  'alparit',
  'ap de cul',
  'ap de suro',
  'diota',
  'erda',
  'es a la merda',
  'ill de puta',
  'illa de puta',
  'ilipolles',
  'ixa',
  'ixar',
  'lepaculs',
  'm cago en tu',
  'mbecil',
  'ocacollons',
  'ollons',
  'ony',
  'orracollons',
  'ostia',
  'osties',
  'ot el camp',
  'ros de quoniam',
  'ue et fotin',
  'ul',
  'uta',
  'utada',
]);
