/**
 * Curated from the CC0 profanity lists published by LDNOOBW.
 *
 * This deliberately excludes medical, identity, and ordinary Catalan words
 * that appear in broad community lists. The purpose is to block clear
 * profanity without turning normal conversation into a false positive.
 */
export const CATALAN_PROFANITY_WORDS: string[] = [
  'cabró',
  'cabrona',
  'cabrones',
  'cabrons',
  'cabro',
  'cagat',
  'cagada',
  'cap de cul',
  'cap de suro',
  'capullo',
  'capulla',
  'carall',
  'carallot',
  'colló',
  'collons',
  'cony',
  'conys',
  'desgraciat',
  'desgraciada',
  'desgraciades',
  'desgraciats',
  'fill de puta',
  'fills de puta',
  'follada',
  'follador',
  'folladora',
  'follant',
  'follat',
  'follats',
  'follades',
  'follar',
  'foteu',
  'fotuda',
  'fotudes',
  'fotut',
  'fotuts',
  'fot el camp',
  'gilipolla',
  'jilipolla',
  'gilipolles',
  'jilipolles',
  'hòstia',
  'ostia',
  'hostia',
  'hòsties',
  'hosties',
  'hostia puta',
  'ostia puta',
  'imbecil',
  'hostia puta',
  'idiota',
  'idiotes',
  'malparit',
  'malparida',
  'malparits',
  'malparides',
  'mamada',
  'mamades',
  'mamó',
  'mamona',
  'merda',
  'merdes',
  'me cago en déu',
  'em cago',
  'em cago en tu',
  'hem cago',
  'que et bombin',
  'que et fotin',
  'que et follin',
  'cagar',
  'retrassat',
  'retrasat',
  'pixar',
  'pixa',
  'puta',
  'putes',
  'putada',
  'putades',
  'putot',
  'putots',
  'recony',
  'subnormal',
  'tros de merda',
  'tros de quòniam',
  'tros de quoniam',
  'tocacollons',
  'torracollons',
  'llepaculs',
  'cul',
  'ves a cagar',
  'ves a la merda',
];
