import { LocaleCode, SUPPORTED_LOCALES, SUPPORTED_LOCALE_CODES } from '../../../core/localization/locale-config';
import { getSeoPath, SeoRouteKey } from '../../../core/localization/seo-routes';
import { LandingSectionContent, SeoLandingContent } from '../models/seo-landing-content.model';

type LocalizedTextByRoute = Readonly<Record<SeoRouteKey, Readonly<Record<LocaleCode, string>>>>;

interface LocaleLandingCopy {
  readonly homeLabel: string;
  readonly eyebrow: string;
  readonly descriptionPrefix: string;
  readonly descriptionSuffix: string;
  readonly primaryCta: string;
  readonly secondaryCta: string;
  readonly trustLabel: string;
  readonly manualValue: string;
  readonly manualLabel: string;
  readonly browserValue: string;
  readonly browserLabel: string;
  readonly overviewTitle: string;
  readonly overviewBodyPrefix: string;
  readonly overviewBodySuffix: string;
  readonly featureTitle: string;
  readonly featureIntro: string;
  readonly featureOneTitle: string;
  readonly featureOneDescription: string;
  readonly featureTwoTitle: string;
  readonly featureTwoDescription: string;
  readonly featureThreeTitle: string;
  readonly featureThreeDescription: string;
  readonly stepsTitle: string;
  readonly stepOneTitle: string;
  readonly stepOneDescription: string;
  readonly stepTwoTitle: string;
  readonly stepTwoDescription: string;
  readonly stepThreeTitle: string;
  readonly stepThreeDescription: string;
  readonly useCasesTitle: string;
  readonly useCasesIntro: string;
  readonly useCaseRemoteTitle: string;
  readonly useCaseRemoteDescription: string;
  readonly useCasePhysicalTitle: string;
  readonly useCasePhysicalDescription: string;
  readonly comparisonTitle: string;
  readonly comparisonIntro: string;
  readonly firstColumnLabel: string;
  readonly secondColumnLabel: string;
  readonly comparisonRowLabel: string;
  readonly comparisonFirstValue: string;
  readonly comparisonSecondValue: string;
  readonly faqTitle: string;
  readonly faqIntro: string;
  readonly faqQuestionPrefix: string;
  readonly faqQuestionSuffix: string;
  readonly faqAnswerPrefix: string;
  readonly faqAnswerSuffix: string;
  readonly ctaTitlePrefix: string;
  readonly ctaDescriptionPrefix: string;
  readonly ctaDescriptionSuffix: string;
  readonly internalLinksTitle: string;
  readonly internalLinksIntro: string;
}

const ROUTE_LABELS: LocalizedTextByRoute = {
  home: {
    es: 'CommanderZone',
    en: 'CommanderZone',
    de: 'CommanderZone',
    fr: 'CommanderZone',
    it: 'CommanderZone',
    pt: 'CommanderZone',
    ja: 'CommanderZone',
    ko: 'CommanderZone',
    'zh-hans': 'CommanderZone',
    'zh-hant': 'CommanderZone',
    nl: 'CommanderZone',
    ca: 'CommanderZone',
    ru: 'CommanderZone',
  },
  playCommanderOnline: {
    es: 'Jugar Commander online',
    en: 'Play Commander online',
    de: 'Commander online spielen',
    fr: 'Jouer a Commander en ligne',
    it: 'Giocare a Commander online',
    pt: 'Jogar Commander online',
    ja: 'Commanderをオンラインで遊ぶ',
    ko: 'Commander 온라인 플레이',
    'zh-hans': '在线玩 Commander',
    'zh-hant': '線上玩 Commander',
    nl: 'Commander online spelen',
    ca: 'Jugar Commander online',
    ru: 'Играть в Commander онлайн',
  },
  playMagicOnlineWithFriends: {
    es: 'Jugar Magic online con amigos',
    en: 'Play Magic online with friends',
    de: 'Magic online mit Freunden spielen',
    fr: 'Jouer a Magic en ligne avec des amis',
    it: 'Giocare a Magic online con amici',
    pt: 'Jogar Magic online com amigos',
    ja: '友達とMagicをオンラインで遊ぶ',
    ko: '친구와 Magic 온라인 플레이',
    'zh-hans': '和朋友在线玩 Magic',
    'zh-hant': '和朋友線上玩 Magic',
    nl: 'Magic online spelen met vrienden',
    ca: 'Jugar Magic online amb amics',
    ru: 'Играть в Magic онлайн с друзьями',
  },
  createCommanderRoom: {
    es: 'Crear sala Commander online',
    en: 'Create a Commander room',
    de: 'Commander-Raum erstellen',
    fr: 'Creer une salle Commander',
    it: 'Creare una stanza Commander',
    pt: 'Criar sala Commander',
    ja: 'Commanderルームを作成',
    ko: 'Commander 방 만들기',
    'zh-hans': '创建 Commander 房间',
    'zh-hant': '建立 Commander 房間',
    nl: 'Commander-kamer maken',
    ca: 'Crear sala Commander',
    ru: 'Создать комнату Commander',
  },
  importCommanderDeck: {
    es: 'Importar mazo Commander',
    en: 'Import a Commander deck',
    de: 'Commander-Deck importieren',
    fr: 'Importer un deck Commander',
    it: 'Importare un mazzo Commander',
    pt: 'Importar deck Commander',
    ja: 'Commanderデッキをインポート',
    ko: 'Commander 덱 가져오기',
    'zh-hans': '导入 Commander 套牌',
    'zh-hant': '匯入 Commander 套牌',
    nl: 'Commander-deck importeren',
    ca: 'Importar baralla Commander',
    ru: 'Импортировать колоду Commander',
  },
  commanderDeckBuilder: {
    es: 'Deck builder Commander',
    en: 'Commander deck builder',
    de: 'Commander Deck Builder',
    fr: 'Constructeur de deck Commander',
    it: 'Deck builder Commander',
    pt: 'Construtor de deck Commander',
    ja: 'Commanderデッキビルダー',
    ko: 'Commander 덱 빌더',
    'zh-hans': 'Commander 套牌构筑器',
    'zh-hant': 'Commander 套牌構築器',
    nl: 'Commander deckbuilder',
    ca: 'Constructor de baralles Commander',
    ru: 'Конструктор колод Commander',
  },
  tableAssistant: {
    es: 'Asistente de mesa para Magic y Commander',
    en: 'Commander life counter and table assistant',
    de: 'MTG Life Counter und Tischassistent',
    fr: 'Compteur de vie MTG et assistant de table',
    it: 'Contatore vite MTG e assistente da tavolo',
    pt: 'Contador de vida MTG e assistente de mesa',
    ja: 'MTGライフカウンターとテーブルアシスタント',
    ko: 'MTG 생명점 카운터와 테이블 도우미',
    'zh-hans': 'MTG 生命计数器和桌面助手',
    'zh-hant': 'MTG 生命計數器和桌面助手',
    nl: 'MTG levens teller en tafelassistent',
    ca: 'Assistent de taula per a Magic i Commander',
    ru: 'Счетчик жизней MTG и помощник стола',
  },
  waysToPlayCommanderOnline: {
    es: 'Formas de jugar Commander online',
    en: 'Ways to play Commander online',
    de: 'Moglichkeiten, Commander online zu spielen',
    fr: 'Facons de jouer a Commander en ligne',
    it: 'Modi per giocare Commander online',
    pt: 'Formas de jogar Commander online',
    ja: 'Commanderをオンラインで遊ぶ方法',
    ko: 'Commander 온라인 플레이 방법',
    'zh-hans': '在线玩 Commander 的方式',
    'zh-hant': '線上玩 Commander 的方式',
    nl: 'Manieren om Commander online te spelen',
    ca: 'Formes de jugar Commander online',
    ru: 'Способы играть в Commander онлайн',
  },
  howToPlayCommanderOnline: {
    es: 'Como jugar Commander online',
    en: 'How to play Commander online',
    de: 'Wie man Commander online spielt',
    fr: 'Comment jouer a Commander en ligne',
    it: 'Come giocare Commander online',
    pt: 'Como jogar Commander online',
    ja: 'Commanderオンラインの遊び方',
    ko: 'Commander 온라인 하는 법',
    'zh-hans': '如何在线玩 Commander',
    'zh-hant': '如何線上玩 Commander',
    nl: 'Hoe speel je Commander online',
    ca: 'Com jugar Commander online',
    ru: 'Как играть в Commander онлайн',
  },
  faq: {
    es: 'FAQ de CommanderZone',
    en: 'CommanderZone FAQ',
    de: 'CommanderZone FAQ',
    fr: 'FAQ CommanderZone',
    it: 'FAQ CommanderZone',
    pt: 'FAQ do CommanderZone',
    ja: 'CommanderZone FAQ',
    ko: 'CommanderZone FAQ',
    'zh-hans': 'CommanderZone 常见问题',
    'zh-hant': 'CommanderZone 常見問題',
    nl: 'CommanderZone FAQ',
    ca: 'FAQ de CommanderZone',
    ru: 'FAQ CommanderZone',
  },
};

const LOCALE_COPY: Readonly<Record<LocaleCode, LocaleLandingCopy>> = {
  es: {
    homeLabel: 'Inicio',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'Pagina publica de CommanderZone para',
    descriptionSuffix: 'con contenido estatico, enlaces rastreables y enfoque en mesas manuales de Commander.',
    primaryCta: 'Crear sala',
    secondaryCta: 'Ver mazos',
    trustLabel: 'Senales clave',
    manualValue: 'Manual',
    manualLabel: 'Los jugadores mantienen el control de la partida.',
    browserValue: 'Navegador',
    browserLabel: 'Pensado para ordenador, tablet y movil.',
    overviewTitle: 'Una experiencia Commander clara',
    overviewBodyPrefix: 'Esta landing explica',
    overviewBodySuffix: 'sin convertir CommanderZone en un motor completo de reglas.',
    featureTitle: 'Funciones relevantes',
    featureIntro: 'Contenido preparado para explicar la intencion SEO de la pagina.',
    featureOneTitle: 'Mesa compartida',
    featureOneDescription: 'Organiza la partida con estado visible y enlaces reales.',
    featureTwoTitle: 'Contenido estatico',
    featureTwoDescription: 'El texto esta disponible para SSR y prerender.',
    featureThreeTitle: 'Separacion limpia',
    featureThreeDescription: 'La landing publica no reutiliza pantallas internas.',
    stepsTitle: 'Como empezar',
    stepOneTitle: 'Elige la pagina',
    stepOneDescription: 'Cada intencion SEO tiene su propio contenido.',
    stepTwoTitle: 'Revisa la informacion',
    stepTwoDescription: 'Las secciones resuelven dudas antes de entrar en la app.',
    stepThreeTitle: 'Entra en CommanderZone',
    stepThreeDescription: 'Los CTA llevan a rutas reales del producto.',
    useCasesTitle: 'Casos de uso',
    useCasesIntro: 'Pensado para grupos que juegan Commander de forma manual.',
    useCaseRemoteTitle: 'Partidas remotas',
    useCaseRemoteDescription: 'Ideal para pods que quieren una mesa online sencilla.',
    useCasePhysicalTitle: 'Partidas fisicas',
    useCasePhysicalDescription: 'El Asistente de mesa ayuda con vidas y dano de comandante.',
    comparisonTitle: 'Comparacion honesta',
    comparisonIntro: 'CommanderZone prioriza mesa manual frente a automatizacion completa.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Motor completo',
    comparisonRowLabel: 'Control de reglas',
    comparisonFirstValue: 'Decisiones manuales del grupo',
    comparisonSecondValue: 'Validacion automatica de jugadas',
    faqTitle: 'Preguntas frecuentes',
    faqIntro: 'Respuestas visibles e indexables para usuarios y buscadores.',
    faqQuestionPrefix: 'Sirve CommanderZone para',
    faqQuestionSuffix: '?',
    faqAnswerPrefix: 'Si. Esta pagina cubre',
    faqAnswerSuffix: 'con contenido publico, estatico y sin traduccion runtime.',
    ctaTitlePrefix: 'Empieza con',
    ctaDescriptionPrefix: 'Usa CommanderZone para',
    ctaDescriptionSuffix: 'y continua en la app cuando quieras jugar.',
    internalLinksTitle: 'Paginas relacionadas',
    internalLinksIntro: 'Enlaces internos SEO hacia otras intenciones aprobadas.',
  },
  en: {
    homeLabel: 'Home',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'A public CommanderZone page for',
    descriptionSuffix: 'with static content, crawlable links and a manual Commander table focus.',
    primaryCta: 'Create room',
    secondaryCta: 'View decks',
    trustLabel: 'Key signals',
    manualValue: 'Manual',
    manualLabel: 'Players keep control of the game.',
    browserValue: 'Browser',
    browserLabel: 'Designed for desktop, tablet and mobile.',
    overviewTitle: 'A clear Commander experience',
    overviewBodyPrefix: 'This landing explains',
    overviewBodySuffix: 'without turning CommanderZone into a full rules engine.',
    featureTitle: 'Relevant features',
    featureIntro: 'Content prepared for the search intent of this page.',
    featureOneTitle: 'Shared table',
    featureOneDescription: 'Run the game with visible state and real links.',
    featureTwoTitle: 'Static content',
    featureTwoDescription: 'The copy is available for SSR and prerender.',
    featureThreeTitle: 'Clean separation',
    featureThreeDescription: 'The public landing does not reuse internal screens.',
    stepsTitle: 'How to start',
    stepOneTitle: 'Choose the page',
    stepOneDescription: 'Each SEO intent has its own content.',
    stepTwoTitle: 'Read the guide',
    stepTwoDescription: 'Sections answer questions before entering the app.',
    stepThreeTitle: 'Open CommanderZone',
    stepThreeDescription: 'CTAs point to real product routes.',
    useCasesTitle: 'Use cases',
    useCasesIntro: 'Built for groups that play Commander manually.',
    useCaseRemoteTitle: 'Remote games',
    useCaseRemoteDescription: 'Useful for pods that want a simple online table.',
    useCasePhysicalTitle: 'Physical games',
    useCasePhysicalDescription: 'The table assistant helps with life totals and commander damage.',
    comparisonTitle: 'Honest comparison',
    comparisonIntro: 'CommanderZone prioritizes a manual table over complete automation.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Full rules engine',
    comparisonRowLabel: 'Rules control',
    comparisonFirstValue: 'Manual group decisions',
    comparisonSecondValue: 'Automated play validation',
    faqTitle: 'Frequently asked questions',
    faqIntro: 'Visible, indexable answers for users and search engines.',
    faqQuestionPrefix: 'Can CommanderZone help with',
    faqQuestionSuffix: '?',
    faqAnswerPrefix: 'Yes. This page covers',
    faqAnswerSuffix: 'with public static content and no runtime translation.',
    ctaTitlePrefix: 'Start with',
    ctaDescriptionPrefix: 'Use CommanderZone for',
    ctaDescriptionSuffix: 'and continue into the app when you are ready to play.',
    internalLinksTitle: 'Related pages',
    internalLinksIntro: 'SEO internal links to other approved search intents.',
  },
  de: {
    homeLabel: 'Startseite',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'Eine offentliche CommanderZone-Seite fur',
    descriptionSuffix: 'mit statischem Inhalt, crawlbaren Links und Fokus auf manuelle Commander-Tische.',
    primaryCta: 'Raum erstellen',
    secondaryCta: 'Decks ansehen',
    trustLabel: 'Wichtige Signale',
    manualValue: 'Manuell',
    manualLabel: 'Die Spieler behalten die Kontrolle uber die Partie.',
    browserValue: 'Browser',
    browserLabel: 'Fur Desktop, Tablet und Mobilgerate gedacht.',
    overviewTitle: 'Eine klare Commander-Erfahrung',
    overviewBodyPrefix: 'Diese Landing erklaert',
    overviewBodySuffix: 'ohne CommanderZone zu einer kompletten Regel-Engine zu machen.',
    featureTitle: 'Relevante Funktionen',
    featureIntro: 'Inhalt fur die Suchintention dieser Seite vorbereitet.',
    featureOneTitle: 'Gemeinsamer Tisch',
    featureOneDescription: 'Spiele mit sichtbarem Zustand und echten Links.',
    featureTwoTitle: 'Statischer Inhalt',
    featureTwoDescription: 'Der Text ist fur SSR und Prerender verfugbar.',
    featureThreeTitle: 'Saubere Trennung',
    featureThreeDescription: 'Die offentliche Landing nutzt keine internen Screens wieder.',
    stepsTitle: 'So startest du',
    stepOneTitle: 'Seite wahlen',
    stepOneDescription: 'Jede SEO-Intention hat eigenen Inhalt.',
    stepTwoTitle: 'Information lesen',
    stepTwoDescription: 'Abschnitte beantworten Fragen vor dem Einstieg in die App.',
    stepThreeTitle: 'CommanderZone offnen',
    stepThreeDescription: 'CTAs verweisen auf echte Produktrouten.',
    useCasesTitle: 'Anwendungsfalle',
    useCasesIntro: 'Fur Gruppen, die Commander manuell spielen.',
    useCaseRemoteTitle: 'Remote-Partien',
    useCaseRemoteDescription: 'Gut fur Pods, die einen einfachen Online-Tisch wollen.',
    useCasePhysicalTitle: 'Physische Partien',
    useCasePhysicalDescription: 'Der Tischassistent hilft mit Lebenspunkten und Commander-Schaden.',
    comparisonTitle: 'Ehrlicher Vergleich',
    comparisonIntro: 'CommanderZone priorisiert den manuellen Tisch statt kompletter Automatisierung.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Vollstandige Regel-Engine',
    comparisonRowLabel: 'Regelkontrolle',
    comparisonFirstValue: 'Manuelle Gruppenentscheidungen',
    comparisonSecondValue: 'Automatische Spielvalidierung',
    faqTitle: 'Haufige Fragen',
    faqIntro: 'Sichtbare und indexierbare Antworten fur Nutzer und Suchmaschinen.',
    faqQuestionPrefix: 'Hilft CommanderZone bei',
    faqQuestionSuffix: '?',
    faqAnswerPrefix: 'Ja. Diese Seite behandelt',
    faqAnswerSuffix: 'mit offentlichem statischem Inhalt und ohne Runtime-Ubersetzung.',
    ctaTitlePrefix: 'Starte mit',
    ctaDescriptionPrefix: 'Nutze CommanderZone fur',
    ctaDescriptionSuffix: 'und gehe in die App, wenn du spielen willst.',
    internalLinksTitle: 'Verwandte Seiten',
    internalLinksIntro: 'SEO-Links zu anderen freigegebenen Suchintentionen.',
  },
  fr: {
    homeLabel: 'Accueil',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'Page publique CommanderZone pour',
    descriptionSuffix: 'avec contenu statique, liens explorables et table Commander manuelle.',
    primaryCta: 'Creer une salle',
    secondaryCta: 'Voir les decks',
    trustLabel: 'Signaux cles',
    manualValue: 'Manuel',
    manualLabel: 'Les joueurs gardent le controle de la partie.',
    browserValue: 'Navigateur',
    browserLabel: 'Pense pour ordinateur, tablette et mobile.',
    overviewTitle: 'Une experience Commander claire',
    overviewBodyPrefix: 'Cette landing explique',
    overviewBodySuffix: 'sans transformer CommanderZone en moteur complet de regles.',
    featureTitle: 'Fonctions utiles',
    featureIntro: 'Contenu prepare pour lintention de recherche de cette page.',
    featureOneTitle: 'Table partagee',
    featureOneDescription: 'Jouez avec un etat visible et des liens reels.',
    featureTwoTitle: 'Contenu statique',
    featureTwoDescription: 'Le texte est disponible pour SSR et prerender.',
    featureThreeTitle: 'Separation claire',
    featureThreeDescription: 'La landing publique ne reutilise pas les ecrans internes.',
    stepsTitle: 'Comment commencer',
    stepOneTitle: 'Choisir la page',
    stepOneDescription: 'Chaque intention SEO a son contenu.',
    stepTwoTitle: 'Lire les infos',
    stepTwoDescription: 'Les sections repondent avant dentrer dans lapp.',
    stepThreeTitle: 'Ouvrir CommanderZone',
    stepThreeDescription: 'Les CTA pointent vers de vraies routes produit.',
    useCasesTitle: 'Cas dusage',
    useCasesIntro: 'Pour les groupes qui jouent Commander manuellement.',
    useCaseRemoteTitle: 'Parties a distance',
    useCaseRemoteDescription: 'Utile pour les pods qui veulent une table online simple.',
    useCasePhysicalTitle: 'Parties physiques',
    useCasePhysicalDescription: 'Lassistant de table aide avec les points de vie et degats de commandant.',
    comparisonTitle: 'Comparaison honnete',
    comparisonIntro: 'CommanderZone privilegie la table manuelle plutot que lautomatisation complete.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Moteur de regles complet',
    comparisonRowLabel: 'Controle des regles',
    comparisonFirstValue: 'Decisions manuelles du groupe',
    comparisonSecondValue: 'Validation automatique des actions',
    faqTitle: 'Questions frequentes',
    faqIntro: 'Reponses visibles et indexables pour utilisateurs et moteurs.',
    faqQuestionPrefix: 'CommanderZone aide-t-il pour',
    faqQuestionSuffix: ' ?',
    faqAnswerPrefix: 'Oui. Cette page couvre',
    faqAnswerSuffix: 'avec un contenu public statique et sans traduction runtime.',
    ctaTitlePrefix: 'Commencer avec',
    ctaDescriptionPrefix: 'Utilisez CommanderZone pour',
    ctaDescriptionSuffix: 'puis entrez dans lapp quand vous voulez jouer.',
    internalLinksTitle: 'Pages liees',
    internalLinksIntro: 'Liens internes SEO vers les autres intentions approuvees.',
  },
  it: {
    homeLabel: 'Home',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'Pagina pubblica CommanderZone per',
    descriptionSuffix: 'con contenuto statico, link scansionabili e focus su tavoli Commander manuali.',
    primaryCta: 'Crea stanza',
    secondaryCta: 'Vedi mazzi',
    trustLabel: 'Segnali chiave',
    manualValue: 'Manuale',
    manualLabel: 'I giocatori mantengono il controllo della partita.',
    browserValue: 'Browser',
    browserLabel: 'Pensato per desktop, tablet e mobile.',
    overviewTitle: 'Unesperienza Commander chiara',
    overviewBodyPrefix: 'Questa landing spiega',
    overviewBodySuffix: 'senza trasformare CommanderZone in un motore completo di regole.',
    featureTitle: 'Funzioni rilevanti',
    featureIntro: 'Contenuto preparato per lintento SEO della pagina.',
    featureOneTitle: 'Tavolo condiviso',
    featureOneDescription: 'Gestisci la partita con stato visibile e link reali.',
    featureTwoTitle: 'Contenuto statico',
    featureTwoDescription: 'Il testo e disponibile per SSR e prerender.',
    featureThreeTitle: 'Separazione pulita',
    featureThreeDescription: 'La landing pubblica non riusa schermate interne.',
    stepsTitle: 'Come iniziare',
    stepOneTitle: 'Scegli la pagina',
    stepOneDescription: 'Ogni intento SEO ha contenuto proprio.',
    stepTwoTitle: 'Leggi le informazioni',
    stepTwoDescription: 'Le sezioni rispondono prima di entrare nellapp.',
    stepThreeTitle: 'Apri CommanderZone',
    stepThreeDescription: 'Le CTA puntano a route reali del prodotto.',
    useCasesTitle: 'Casi duso',
    useCasesIntro: 'Per gruppi che giocano Commander in modo manuale.',
    useCaseRemoteTitle: 'Partite remote',
    useCaseRemoteDescription: 'Utile per pod che vogliono un tavolo online semplice.',
    useCasePhysicalTitle: 'Partite fisiche',
    useCasePhysicalDescription: 'Lassistente da tavolo aiuta con vite e danni da comandante.',
    comparisonTitle: 'Confronto onesto',
    comparisonIntro: 'CommanderZone privilegia il tavolo manuale rispetto allautomazione completa.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Motore regole completo',
    comparisonRowLabel: 'Controllo regole',
    comparisonFirstValue: 'Decisioni manuali del gruppo',
    comparisonSecondValue: 'Validazione automatica delle giocate',
    faqTitle: 'Domande frequenti',
    faqIntro: 'Risposte visibili e indicizzabili per utenti e motori.',
    faqQuestionPrefix: 'CommanderZone aiuta con',
    faqQuestionSuffix: '?',
    faqAnswerPrefix: 'Si. Questa pagina copre',
    faqAnswerSuffix: 'con contenuto pubblico statico e senza traduzione runtime.',
    ctaTitlePrefix: 'Inizia con',
    ctaDescriptionPrefix: 'Usa CommanderZone per',
    ctaDescriptionSuffix: 'e continua nellapp quando vuoi giocare.',
    internalLinksTitle: 'Pagine correlate',
    internalLinksIntro: 'Link interni SEO verso altre intenzioni approvate.',
  },
  pt: {
    homeLabel: 'Inicio',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'Pagina publica do CommanderZone para',
    descriptionSuffix: 'com conteudo estatico, links rastreaveis e foco em mesas manuais de Commander.',
    primaryCta: 'Criar sala',
    secondaryCta: 'Ver decks',
    trustLabel: 'Sinais principais',
    manualValue: 'Manual',
    manualLabel: 'Os jogadores mantem controle da partida.',
    browserValue: 'Navegador',
    browserLabel: 'Pensado para desktop, tablet e celular.',
    overviewTitle: 'Uma experiencia Commander clara',
    overviewBodyPrefix: 'Esta landing explica',
    overviewBodySuffix: 'sem transformar CommanderZone em um motor completo de regras.',
    featureTitle: 'Recursos relevantes',
    featureIntro: 'Conteudo preparado para a intencao SEO desta pagina.',
    featureOneTitle: 'Mesa compartilhada',
    featureOneDescription: 'Jogue com estado visivel e links reais.',
    featureTwoTitle: 'Conteudo estatico',
    featureTwoDescription: 'O texto esta disponivel para SSR e prerender.',
    featureThreeTitle: 'Separacao limpa',
    featureThreeDescription: 'A landing publica nao reutiliza telas internas.',
    stepsTitle: 'Como comecar',
    stepOneTitle: 'Escolha a pagina',
    stepOneDescription: 'Cada intencao SEO tem conteudo proprio.',
    stepTwoTitle: 'Leia as informacoes',
    stepTwoDescription: 'As secoes respondem antes de entrar no app.',
    stepThreeTitle: 'Abra CommanderZone',
    stepThreeDescription: 'As CTAs apontam para rotas reais do produto.',
    useCasesTitle: 'Casos de uso',
    useCasesIntro: 'Para grupos que jogam Commander manualmente.',
    useCaseRemoteTitle: 'Partidas remotas',
    useCaseRemoteDescription: 'Util para pods que querem uma mesa online simples.',
    useCasePhysicalTitle: 'Partidas fisicas',
    useCasePhysicalDescription: 'O assistente de mesa ajuda com vidas e dano de comandante.',
    comparisonTitle: 'Comparacao honesta',
    comparisonIntro: 'CommanderZone prioriza mesa manual em vez de automacao completa.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Motor completo',
    comparisonRowLabel: 'Controle de regras',
    comparisonFirstValue: 'Decisoes manuais do grupo',
    comparisonSecondValue: 'Validacao automatica de jogadas',
    faqTitle: 'Perguntas frequentes',
    faqIntro: 'Respostas visiveis e indexaveis para usuarios e buscadores.',
    faqQuestionPrefix: 'CommanderZone ajuda com',
    faqQuestionSuffix: '?',
    faqAnswerPrefix: 'Sim. Esta pagina cobre',
    faqAnswerSuffix: 'com conteudo publico estatico e sem traducao runtime.',
    ctaTitlePrefix: 'Comece com',
    ctaDescriptionPrefix: 'Use CommanderZone para',
    ctaDescriptionSuffix: 'e continue no app quando quiser jogar.',
    internalLinksTitle: 'Paginas relacionadas',
    internalLinksIntro: 'Links internos SEO para outras intencoes aprovadas.',
  },
  ja: {
    homeLabel: 'ホーム',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'CommanderZoneの公開ページ:',
    descriptionSuffix: '静的コンテンツ、クロール可能なリンク、手動Commanderテーブル向けです。',
    primaryCta: 'ルーム作成',
    secondaryCta: 'デッキを見る',
    trustLabel: '主要ポイント',
    manualValue: '手動',
    manualLabel: 'プレイヤーがゲームを管理します。',
    browserValue: 'ブラウザ',
    browserLabel: 'PC、タブレット、モバイル向けです。',
    overviewTitle: 'わかりやすいCommander体験',
    overviewBodyPrefix: 'このランディングは',
    overviewBodySuffix: 'を説明し、完全なルールエンジンにはしません。',
    featureTitle: '関連機能',
    featureIntro: 'この検索意図に合わせた静的コンテンツです。',
    featureOneTitle: '共有テーブル',
    featureOneDescription: '状態を見ながら実リンクで進めます。',
    featureTwoTitle: '静的コンテンツ',
    featureTwoDescription: 'SSRとprerenderで利用できます。',
    featureThreeTitle: '明確な分離',
    featureThreeDescription: '公開ランディングは内部画面を再利用しません。',
    stepsTitle: '始め方',
    stepOneTitle: 'ページを選ぶ',
    stepOneDescription: 'SEO意図ごとに内容があります。',
    stepTwoTitle: '情報を読む',
    stepTwoDescription: 'アプリに入る前に疑問を解決します。',
    stepThreeTitle: 'CommanderZoneを開く',
    stepThreeDescription: 'CTAは実際の製品ルートに進みます。',
    useCasesTitle: '利用シーン',
    useCasesIntro: '手動でCommanderを遊ぶグループ向けです。',
    useCaseRemoteTitle: 'リモートゲーム',
    useCaseRemoteDescription: 'シンプルなオンライン卓が必要なpodに向いています。',
    useCasePhysicalTitle: '紙のゲーム',
    useCasePhysicalDescription: 'テーブルアシスタントがライフとCommanderダメージを助けます。',
    comparisonTitle: '正直な比較',
    comparisonIntro: 'CommanderZoneは完全自動化より手動テーブルを重視します。',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: '完全ルールエンジン',
    comparisonRowLabel: 'ルール管理',
    comparisonFirstValue: 'グループの手動判断',
    comparisonSecondValue: '自動プレイ検証',
    faqTitle: 'よくある質問',
    faqIntro: 'ユーザーと検索エンジン向けの可視FAQです。',
    faqQuestionPrefix: 'CommanderZoneは',
    faqQuestionSuffix: 'に使えますか?',
    faqAnswerPrefix: 'はい。このページは',
    faqAnswerSuffix: 'を公開静的コンテンツで扱い、runtime翻訳を使いません。',
    ctaTitlePrefix: '始める:',
    ctaDescriptionPrefix: 'CommanderZoneで',
    ctaDescriptionSuffix: 'を使い、準備できたらアプリへ進めます。',
    internalLinksTitle: '関連ページ',
    internalLinksIntro: '承認済みSEO意図への内部リンクです。',
  },
  ko: {
    homeLabel: '홈',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'CommanderZone 공개 페이지:',
    descriptionSuffix: '정적 콘텐츠, 크롤 가능한 링크, 수동 Commander 테이블에 맞춥니다.',
    primaryCta: '방 만들기',
    secondaryCta: '덱 보기',
    trustLabel: '핵심 신호',
    manualValue: '수동',
    manualLabel: '플레이어가 게임을 직접 관리합니다.',
    browserValue: '브라우저',
    browserLabel: '데스크톱, 태블릿, 모바일용입니다.',
    overviewTitle: '명확한 Commander 경험',
    overviewBodyPrefix: '이 랜딩은',
    overviewBodySuffix: '을 설명하며 완전한 규칙 엔진으로 바꾸지 않습니다.',
    featureTitle: '관련 기능',
    featureIntro: '이 검색 의도에 맞춘 정적 콘텐츠입니다.',
    featureOneTitle: '공유 테이블',
    featureOneDescription: '보이는 상태와 실제 링크로 진행합니다.',
    featureTwoTitle: '정적 콘텐츠',
    featureTwoDescription: 'SSR과 prerender에서 사용할 수 있습니다.',
    featureThreeTitle: '명확한 분리',
    featureThreeDescription: '공개 랜딩은 내부 화면을 재사용하지 않습니다.',
    stepsTitle: '시작 방법',
    stepOneTitle: '페이지 선택',
    stepOneDescription: '각 SEO 의도는 자체 콘텐츠가 있습니다.',
    stepTwoTitle: '정보 확인',
    stepTwoDescription: '앱에 들어가기 전에 질문을 해결합니다.',
    stepThreeTitle: 'CommanderZone 열기',
    stepThreeDescription: 'CTA는 실제 제품 경로로 연결됩니다.',
    useCasesTitle: '사용 사례',
    useCasesIntro: 'Commander를 수동으로 플레이하는 그룹을 위한 구성입니다.',
    useCaseRemoteTitle: '원격 게임',
    useCaseRemoteDescription: '간단한 온라인 테이블이 필요한 pod에 적합합니다.',
    useCasePhysicalTitle: '오프라인 게임',
    useCasePhysicalDescription: '테이블 도우미는 생명점과 commander 피해를 돕습니다.',
    comparisonTitle: '정직한 비교',
    comparisonIntro: 'CommanderZone은 완전 자동화보다 수동 테이블을 우선합니다.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: '전체 규칙 엔진',
    comparisonRowLabel: '규칙 제어',
    comparisonFirstValue: '그룹의 수동 결정',
    comparisonSecondValue: '자동 플레이 검증',
    faqTitle: '자주 묻는 질문',
    faqIntro: '사용자와 검색 엔진을 위한 보이는 답변입니다.',
    faqQuestionPrefix: 'CommanderZone은',
    faqQuestionSuffix: '에 도움이 되나요?',
    faqAnswerPrefix: '예. 이 페이지는',
    faqAnswerSuffix: '을 공개 정적 콘텐츠로 다루며 runtime 번역을 쓰지 않습니다.',
    ctaTitlePrefix: '시작:',
    ctaDescriptionPrefix: 'CommanderZone으로',
    ctaDescriptionSuffix: '을 사용하고 준비되면 앱으로 이동하세요.',
    internalLinksTitle: '관련 페이지',
    internalLinksIntro: '승인된 다른 SEO 의도에 대한 내부 링크입니다.',
  },
  'zh-hans': {
    homeLabel: '首页',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'CommanderZone 公开页面:',
    descriptionSuffix: '包含静态内容、可抓取链接，并面向手动 Commander 桌面。',
    primaryCta: '创建房间',
    secondaryCta: '查看套牌',
    trustLabel: '关键信号',
    manualValue: '手动',
    manualLabel: '玩家保留对游戏的控制。',
    browserValue: '浏览器',
    browserLabel: '适合桌面、平板和手机。',
    overviewTitle: '清晰的 Commander 体验',
    overviewBodyPrefix: '此落地页说明',
    overviewBodySuffix: '，不会把 CommanderZone 变成完整规则引擎。',
    featureTitle: '相关功能',
    featureIntro: '为此搜索意图准备的静态内容。',
    featureOneTitle: '共享桌面',
    featureOneDescription: '通过可见状态和真实链接进行游戏。',
    featureTwoTitle: '静态内容',
    featureTwoDescription: '文本可用于 SSR 和 prerender。',
    featureThreeTitle: '清晰分离',
    featureThreeDescription: '公开落地页不复用内部界面。',
    stepsTitle: '如何开始',
    stepOneTitle: '选择页面',
    stepOneDescription: '每个 SEO 意图都有自己的内容。',
    stepTwoTitle: '阅读信息',
    stepTwoDescription: '进入应用前先解决问题。',
    stepThreeTitle: '打开 CommanderZone',
    stepThreeDescription: 'CTA 指向真实产品路由。',
    useCasesTitle: '使用场景',
    useCasesIntro: '适合手动玩 Commander 的小组。',
    useCaseRemoteTitle: '远程游戏',
    useCaseRemoteDescription: '适合需要简单在线桌面的 pod。',
    useCasePhysicalTitle: '实体游戏',
    useCasePhysicalDescription: '桌面助手帮助记录生命和指挥官伤害。',
    comparisonTitle: '诚实比较',
    comparisonIntro: 'CommanderZone 优先手动桌面，而不是完全自动化。',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: '完整规则引擎',
    comparisonRowLabel: '规则控制',
    comparisonFirstValue: '小组手动决定',
    comparisonSecondValue: '自动验证操作',
    faqTitle: '常见问题',
    faqIntro: '面向用户和搜索引擎的可见答案。',
    faqQuestionPrefix: 'CommanderZone 能帮助',
    faqQuestionSuffix: '吗?',
    faqAnswerPrefix: '可以。此页面用公开静态内容介绍',
    faqAnswerSuffix: '，不使用 runtime 翻译。',
    ctaTitlePrefix: '开始:',
    ctaDescriptionPrefix: '使用 CommanderZone 进行',
    ctaDescriptionSuffix: '，准备好后进入应用。',
    internalLinksTitle: '相关页面',
    internalLinksIntro: '指向其他已批准 SEO 意图的内部链接。',
  },
  'zh-hant': {
    homeLabel: '首頁',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'CommanderZone 公開頁面:',
    descriptionSuffix: '包含靜態內容、可抓取連結，並面向手動 Commander 桌面。',
    primaryCta: '建立房間',
    secondaryCta: '查看套牌',
    trustLabel: '關鍵訊號',
    manualValue: '手動',
    manualLabel: '玩家保留對遊戲的控制。',
    browserValue: '瀏覽器',
    browserLabel: '適合桌面、平板和手機。',
    overviewTitle: '清晰的 Commander 體驗',
    overviewBodyPrefix: '此落地頁說明',
    overviewBodySuffix: '，不會把 CommanderZone 變成完整規則引擎。',
    featureTitle: '相關功能',
    featureIntro: '為此搜尋意圖準備的靜態內容。',
    featureOneTitle: '共享桌面',
    featureOneDescription: '透過可見狀態和真實連結進行遊戲。',
    featureTwoTitle: '靜態內容',
    featureTwoDescription: '文字可用於 SSR 和 prerender。',
    featureThreeTitle: '清晰分離',
    featureThreeDescription: '公開落地頁不複用內部介面。',
    stepsTitle: '如何開始',
    stepOneTitle: '選擇頁面',
    stepOneDescription: '每個 SEO 意圖都有自己的內容。',
    stepTwoTitle: '閱讀資訊',
    stepTwoDescription: '進入應用前先解決問題。',
    stepThreeTitle: '開啟 CommanderZone',
    stepThreeDescription: 'CTA 指向真實產品路由。',
    useCasesTitle: '使用場景',
    useCasesIntro: '適合手動玩 Commander 的小組。',
    useCaseRemoteTitle: '遠端遊戲',
    useCaseRemoteDescription: '適合需要簡單線上桌面的 pod。',
    useCasePhysicalTitle: '實體遊戲',
    useCasePhysicalDescription: '桌面助手幫助記錄生命和指揮官傷害。',
    comparisonTitle: '誠實比較',
    comparisonIntro: 'CommanderZone 優先手動桌面，而不是完全自動化。',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: '完整規則引擎',
    comparisonRowLabel: '規則控制',
    comparisonFirstValue: '小組手動決定',
    comparisonSecondValue: '自動驗證操作',
    faqTitle: '常見問題',
    faqIntro: '面向使用者和搜尋引擎的可見答案。',
    faqQuestionPrefix: 'CommanderZone 能幫助',
    faqQuestionSuffix: '嗎?',
    faqAnswerPrefix: '可以。此頁面用公開靜態內容介紹',
    faqAnswerSuffix: '，不使用 runtime 翻譯。',
    ctaTitlePrefix: '開始:',
    ctaDescriptionPrefix: '使用 CommanderZone 進行',
    ctaDescriptionSuffix: '，準備好後進入應用。',
    internalLinksTitle: '相關頁面',
    internalLinksIntro: '指向其他已批准 SEO 意圖的內部連結。',
  },
  nl: {
    homeLabel: 'Home',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'Openbare CommanderZone-pagina voor',
    descriptionSuffix: 'met statische content, crawlbare links en focus op handmatige Commander-tafels.',
    primaryCta: 'Kamer maken',
    secondaryCta: 'Decks bekijken',
    trustLabel: 'Belangrijke signalen',
    manualValue: 'Handmatig',
    manualLabel: 'Spelers houden controle over de partij.',
    browserValue: 'Browser',
    browserLabel: 'Ontworpen voor desktop, tablet en mobiel.',
    overviewTitle: 'Een duidelijke Commander-ervaring',
    overviewBodyPrefix: 'Deze landing legt uit',
    overviewBodySuffix: 'zonder CommanderZone een volledige regels-engine te maken.',
    featureTitle: 'Relevante functies',
    featureIntro: 'Content voor de zoekintentie van deze pagina.',
    featureOneTitle: 'Gedeelde tafel',
    featureOneDescription: 'Speel met zichtbare status en echte links.',
    featureTwoTitle: 'Statische content',
    featureTwoDescription: 'De tekst is beschikbaar voor SSR en prerender.',
    featureThreeTitle: 'Heldere scheiding',
    featureThreeDescription: 'De openbare landing hergebruikt geen interne schermen.',
    stepsTitle: 'Hoe te starten',
    stepOneTitle: 'Kies de pagina',
    stepOneDescription: 'Elke SEO-intentie heeft eigen content.',
    stepTwoTitle: 'Lees de info',
    stepTwoDescription: 'Secties beantwoorden vragen voor je de app opent.',
    stepThreeTitle: 'Open CommanderZone',
    stepThreeDescription: 'CTAs wijzen naar echte productroutes.',
    useCasesTitle: 'Gebruikssituaties',
    useCasesIntro: 'Voor groepen die Commander handmatig spelen.',
    useCaseRemoteTitle: 'Remote games',
    useCaseRemoteDescription: 'Handig voor pods die een simpele online tafel willen.',
    useCasePhysicalTitle: 'Fysieke games',
    useCasePhysicalDescription: 'De tafelassistent helpt met levens en commander damage.',
    comparisonTitle: 'Eerlijke vergelijking',
    comparisonIntro: 'CommanderZone kiest voor een handmatige tafel boven volledige automatisering.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Volledige regels-engine',
    comparisonRowLabel: 'Regelcontrole',
    comparisonFirstValue: 'Handmatige groepsbeslissingen',
    comparisonSecondValue: 'Automatische validatie',
    faqTitle: 'Veelgestelde vragen',
    faqIntro: 'Zichtbare en indexeerbare antwoorden voor gebruikers en zoekmachines.',
    faqQuestionPrefix: 'Helpt CommanderZone met',
    faqQuestionSuffix: '?',
    faqAnswerPrefix: 'Ja. Deze pagina behandelt',
    faqAnswerSuffix: 'met openbare statische content en zonder runtime vertaling.',
    ctaTitlePrefix: 'Start met',
    ctaDescriptionPrefix: 'Gebruik CommanderZone voor',
    ctaDescriptionSuffix: 'en ga verder in de app wanneer je wilt spelen.',
    internalLinksTitle: 'Gerelateerde paginas',
    internalLinksIntro: 'SEO interne links naar andere goedgekeurde zoekintenties.',
  },
  ca: {
    homeLabel: 'Inici',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'Pagina publica de CommanderZone per a',
    descriptionSuffix: 'amb contingut estatic, enllacos rastrejables i enfoc en taules manuals de Commander.',
    primaryCta: 'Crear sala',
    secondaryCta: 'Veure baralles',
    trustLabel: 'Senyals clau',
    manualValue: 'Manual',
    manualLabel: 'Els jugadors mantenen el control de la partida.',
    browserValue: 'Navegador',
    browserLabel: 'Pensat per ordinador, tauleta i mobil.',
    overviewTitle: 'Una experiencia Commander clara',
    overviewBodyPrefix: 'Aquesta landing explica',
    overviewBodySuffix: 'sense convertir CommanderZone en un motor complet de regles.',
    featureTitle: 'Funcions rellevants',
    featureIntro: 'Contingut preparat per a la intencio SEO daquesta pagina.',
    featureOneTitle: 'Taula compartida',
    featureOneDescription: 'Juga amb estat visible i enllacos reals.',
    featureTwoTitle: 'Contingut estatic',
    featureTwoDescription: 'El text esta disponible per SSR i prerender.',
    featureThreeTitle: 'Separacio neta',
    featureThreeDescription: 'La landing publica no reutilitza pantalles internes.',
    stepsTitle: 'Com comencar',
    stepOneTitle: 'Tria la pagina',
    stepOneDescription: 'Cada intencio SEO te contingut propi.',
    stepTwoTitle: 'Llegeix la informacio',
    stepTwoDescription: 'Les seccions resolen dubtes abans dentrar a lapp.',
    stepThreeTitle: 'Obre CommanderZone',
    stepThreeDescription: 'Els CTA porten a rutes reals del producte.',
    useCasesTitle: 'Casos dus',
    useCasesIntro: 'Per a grups que juguen Commander manualment.',
    useCaseRemoteTitle: 'Partides remotes',
    useCaseRemoteDescription: 'Util per a pods que volen una taula online senzilla.',
    useCasePhysicalTitle: 'Partides fisiques',
    useCasePhysicalDescription: 'Lassistent de taula ajuda amb vides i dany de comandant.',
    comparisonTitle: 'Comparacio honesta',
    comparisonIntro: 'CommanderZone prioritza la taula manual davant lautomatitzacio completa.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Motor complet',
    comparisonRowLabel: 'Control de regles',
    comparisonFirstValue: 'Decisions manuals del grup',
    comparisonSecondValue: 'Validacio automatica de jugades',
    faqTitle: 'Preguntes frequents',
    faqIntro: 'Respostes visibles i indexables per a usuaris i cercadors.',
    faqQuestionPrefix: 'Serveix CommanderZone per a',
    faqQuestionSuffix: '?',
    faqAnswerPrefix: 'Si. Aquesta pagina cobreix',
    faqAnswerSuffix: 'amb contingut public estatic i sense traduccio runtime.',
    ctaTitlePrefix: 'Comenca amb',
    ctaDescriptionPrefix: 'Utilitza CommanderZone per a',
    ctaDescriptionSuffix: 'i continua a lapp quan vulguis jugar.',
    internalLinksTitle: 'Pagines relacionades',
    internalLinksIntro: 'Enllacos interns SEO cap a altres intencions aprovades.',
  },
  ru: {
    homeLabel: 'Главная',
    eyebrow: 'CommanderZone SEO',
    descriptionPrefix: 'Публичная страница CommanderZone для',
    descriptionSuffix: 'со статическим контентом, индексируемыми ссылками и фокусом на ручных столах Commander.',
    primaryCta: 'Создать комнату',
    secondaryCta: 'Смотреть колоды',
    trustLabel: 'Ключевые сигналы',
    manualValue: 'Ручной режим',
    manualLabel: 'Игроки сохраняют контроль над партией.',
    browserValue: 'Браузер',
    browserLabel: 'Подходит для компьютера, планшета и телефона.',
    overviewTitle: 'Понятный опыт Commander',
    overviewBodyPrefix: 'Эта landing-страница объясняет',
    overviewBodySuffix: 'не превращая CommanderZone в полноценный движок правил.',
    featureTitle: 'Полезные функции',
    featureIntro: 'Контент подготовлен под поисковое намерение этой страницы.',
    featureOneTitle: 'Общий стол',
    featureOneDescription: 'Играйте с видимым состоянием и настоящими ссылками.',
    featureTwoTitle: 'Статический контент',
    featureTwoDescription: 'Текст доступен для SSR и prerender.',
    featureThreeTitle: 'Чистое разделение',
    featureThreeDescription: 'Публичная landing-страница не использует внутренние экраны.',
    stepsTitle: 'Как начать',
    stepOneTitle: 'Выберите страницу',
    stepOneDescription: 'У каждого SEO-намерения есть свой контент.',
    stepTwoTitle: 'Прочитайте информацию',
    stepTwoDescription: 'Разделы отвечают на вопросы до входа в приложение.',
    stepThreeTitle: 'Откройте CommanderZone',
    stepThreeDescription: 'CTA ведут на реальные маршруты продукта.',
    useCasesTitle: 'Сценарии использования',
    useCasesIntro: 'Для групп, которые играют Commander вручную.',
    useCaseRemoteTitle: 'Удаленные партии',
    useCaseRemoteDescription: 'Подходит pods, которым нужен простой онлайн-стол.',
    useCasePhysicalTitle: 'Физические партии',
    useCasePhysicalDescription: 'Помощник стола помогает с жизнями и уроном командира.',
    comparisonTitle: 'Честное сравнение',
    comparisonIntro: 'CommanderZone выбирает ручной стол вместо полной автоматизации.',
    firstColumnLabel: 'CommanderZone',
    secondColumnLabel: 'Полный движок правил',
    comparisonRowLabel: 'Контроль правил',
    comparisonFirstValue: 'Ручные решения группы',
    comparisonSecondValue: 'Автоматическая проверка ходов',
    faqTitle: 'Частые вопросы',
    faqIntro: 'Видимые и индексируемые ответы для пользователей и поисковых систем.',
    faqQuestionPrefix: 'Помогает ли CommanderZone с',
    faqQuestionSuffix: '?',
    faqAnswerPrefix: 'Да. Эта страница описывает',
    faqAnswerSuffix: 'через публичный статический контент без runtime-перевода.',
    ctaTitlePrefix: 'Начните с',
    ctaDescriptionPrefix: 'Используйте CommanderZone для',
    ctaDescriptionSuffix: 'и переходите в приложение, когда будете готовы играть.',
    internalLinksTitle: 'Связанные страницы',
    internalLinksIntro: 'SEO-ссылки на другие утвержденные поисковые намерения.',
  },
};

export function createSeoLandingContentByLocale(routeKey: SeoRouteKey): Readonly<Record<LocaleCode, SeoLandingContent>> {
  return Object.fromEntries(
    SUPPORTED_LOCALE_CODES.map((locale) => [locale, createSeoLandingContent(routeKey, locale)]),
  ) as Record<LocaleCode, SeoLandingContent>;
}

function createSeoLandingContent(routeKey: SeoRouteKey, locale: LocaleCode): SeoLandingContent {
  const copy = LOCALE_COPY[locale];
  const title = ROUTE_LABELS[routeKey][locale];
  const path = getSeoPath(routeKey, locale);
  const description = `${copy.descriptionPrefix} ${title} ${copy.descriptionSuffix}`;
  const faq = routeKey === 'faq'
    ? createPublicFaqContent(locale, copy)
    : createLandingFaqContent(title, copy);

  return {
    routeKey,
    locale,
    seo: {
      title: `${title} | CommanderZone`,
      description,
      ogTitle: `${title} | CommanderZone`,
      ogDescription: description,
      ogImage: getOpenGraphImagePath(routeKey),
    },
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': routeKey === 'faq' ? 'FAQPage' : 'WebPage',
      name: title,
      description,
      inLanguage: locale,
      url: path,
      mainEntity: faq.items.map((item) => ({
        '@type': 'Question',
        name: item.question,
        acceptedAnswer: {
          '@type': 'Answer',
          text: item.answer.join(' '),
        },
      })),
    },
    siteName: 'CommanderZone',
    homeLink: { label: copy.homeLabel, href: getSeoPath('home', locale) },
    publicNavigationLinks: [
      { label: ROUTE_LABELS.playCommanderOnline[locale], href: getSeoPath('playCommanderOnline', locale) },
      { label: ROUTE_LABELS.faq[locale], href: getSeoPath('faq', locale) },
    ],
    footerLinks: [
      { label: ROUTE_LABELS.faq[locale], href: getSeoPath('faq', locale) },
      { label: ROUTE_LABELS.tableAssistant[locale], href: getSeoPath('tableAssistant', locale) },
      { label: ROUTE_LABELS.importCommanderDeck[locale], href: getSeoPath('importCommanderDeck', locale) },
    ],
    localeLinks: SUPPORTED_LOCALES.map((supportedLocale) => ({
      locale: supportedLocale.code,
      label: supportedLocale.nativeLabel,
      href: getSeoPath(routeKey, supportedLocale.code),
      ariaLabel: supportedLocale.label,
    })),
    breadcrumb: {
      items: [
        { label: copy.homeLabel, href: getSeoPath('home', locale) },
        { label: title, href: path },
      ],
    },
    hero: {
      eyebrow: copy.eyebrow,
      title,
      subtitle: description,
      primaryLink: { label: copy.primaryCta, href: '/rooms' },
      secondaryLink: { label: copy.secondaryCta, href: '/decks' },
      highlights: [copy.manualLabel, copy.browserLabel],
    },
    trustBar: {
      label: copy.trustLabel,
      items: [
        { value: copy.manualValue, label: copy.manualLabel },
        { value: copy.browserValue, label: copy.browserLabel },
      ],
    },
    sections: [
      {
        id: 'overview',
        title: copy.overviewTitle,
        body: [
          `${copy.overviewBodyPrefix} ${title} ${copy.overviewBodySuffix}`,
          description,
        ],
      },
      ...getRouteSpecificSections(routeKey, locale),
    ],
    featureGrid: {
      id: 'features',
      title: copy.featureTitle,
      intro: copy.featureIntro,
      features: [
        { title: copy.featureOneTitle, description: copy.featureOneDescription },
        { title: copy.featureTwoTitle, description: copy.featureTwoDescription },
        { title: copy.featureThreeTitle, description: copy.featureThreeDescription },
      ],
    },
    steps: {
      id: 'start',
      title: copy.stepsTitle,
      steps: [
        { title: copy.stepOneTitle, description: copy.stepOneDescription },
        { title: copy.stepTwoTitle, description: copy.stepTwoDescription },
        { title: copy.stepThreeTitle, description: copy.stepThreeDescription },
      ],
    },
    useCases: {
      id: 'use-cases',
      title: copy.useCasesTitle,
      intro: copy.useCasesIntro,
      useCases: [
        { title: copy.useCaseRemoteTitle, description: copy.useCaseRemoteDescription },
        { title: copy.useCasePhysicalTitle, description: copy.useCasePhysicalDescription },
      ],
    },
    comparison: {
      id: 'comparison',
      title: copy.comparisonTitle,
      intro: copy.comparisonIntro,
      firstColumnLabel: copy.firstColumnLabel,
      secondColumnLabel: copy.secondColumnLabel,
      rows: [
        {
          label: copy.comparisonRowLabel,
          firstValue: copy.comparisonFirstValue,
          secondValue: copy.comparisonSecondValue,
        },
      ],
    },
    faqPreview: {
      id: 'quick-faq',
      title: copy.faqTitle,
      intro: copy.faqIntro,
      items: faq.items.slice(0, 1),
    },
    fullFaq: faq,
    faq,
    cta: {
      id: 'cta',
      title: `${copy.ctaTitlePrefix} ${title}`,
      description: `${copy.ctaDescriptionPrefix} ${title} ${copy.ctaDescriptionSuffix}`,
      primaryLink: { label: copy.primaryCta, href: '/rooms' },
      secondaryLink: { label: copy.secondaryCta, href: '/decks' },
    },
    internalLinks: {
      id: 'related',
      title: copy.internalLinksTitle,
      intro: copy.internalLinksIntro,
      links: getRelatedRouteKeys(routeKey).map((relatedRouteKey) => ({
        label: ROUTE_LABELS[relatedRouteKey][locale],
        href: getSeoPath(relatedRouteKey, locale),
      })),
    },
  };
}

function createLandingFaqContent(title: string, copy: LocaleLandingCopy): SeoLandingContent['faq'] {
  return {
    id: 'faq',
    title: copy.faqTitle,
    intro: copy.faqIntro,
    items: [
      {
        question: `${copy.faqQuestionPrefix} ${title}${copy.faqQuestionSuffix}`,
        answer: [`${copy.faqAnswerPrefix} ${title} ${copy.faqAnswerSuffix}`],
      },
      {
        question: `${copy.comparisonTitle}: ${title}`,
        answer: [`${copy.comparisonIntro} ${copy.comparisonFirstValue}.`],
      },
    ],
  };
}

function createPublicFaqContent(locale: LocaleCode, copy: LocaleLandingCopy): SeoLandingContent['faq'] {
  const questions = PUBLIC_FAQ_QUESTIONS[locale];
  const localizedQuestions = questions.length > 0 ? questions : createLocalizedPublicFaqQuestions(locale, copy);

  return {
    id: 'faq',
    title: copy.faqTitle,
    intro: copy.faqIntro,
    items: localizedQuestions.map((question, index) => ({
      question,
      answer: [createPublicFaqAnswer(question, index, copy)],
    })),
  };
}

function createPublicFaqAnswer(question: string, index: number, copy: LocaleLandingCopy): string {
  const answerGroups = [
    `${copy.faqAnswerPrefix} CommanderZone ${copy.faqAnswerSuffix}`,
    `${copy.comparisonIntro} ${copy.comparisonFirstValue}.`,
    `${copy.useCaseRemoteDescription} ${copy.useCasePhysicalDescription}`,
    `${copy.featureTwoDescription} ${copy.featureThreeDescription}`,
  ];

  return `${answerGroups[index % answerGroups.length]} ${question}`;
}

function createLocalizedPublicFaqQuestions(locale: LocaleCode, copy: LocaleLandingCopy): readonly string[] {
  const commanderOnline = ROUTE_LABELS.playCommanderOnline[locale];
  const magicWithFriends = ROUTE_LABELS.playMagicOnlineWithFriends[locale];
  const createRoom = ROUTE_LABELS.createCommanderRoom[locale];
  const importDeck = ROUTE_LABELS.importCommanderDeck[locale];
  const deckBuilder = ROUTE_LABELS.commanderDeckBuilder[locale];
  const tableAssistant = ROUTE_LABELS.tableAssistant[locale];
  const waysToPlay = ROUTE_LABELS.waysToPlayCommanderOnline[locale];

  return [
    `${copy.faqQuestionPrefix} CommanderZone${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${commanderOnline}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${magicWithFriends}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${copy.browserValue}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${copy.browserLabel}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${createRoom}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} invitations and room links${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} free Commander games${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} accounts and room creation${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} multiplayer Commander${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${importDeck}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} pasted decklists${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${deckBuilder}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} creating Commander decks from scratch${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} editing decks before playing${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} Moxfield, Archidekt and other deck sources${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} decklist formats${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} existing Commander decks online${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${tableAssistant}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} physical Magic games${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} phone life counter use${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} tablet table assistant use${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} in-person games${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} commander damage tracking${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} several player life totals${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} poison or infect tracking${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} table assistant without online room${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} SpellTable comparison${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} Cockatrice comparison${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} MTGO comparison${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} MTG Arena comparison${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} Untap.in comparison${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} EDHPlay comparison${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} ${waysToPlay}${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} mobile devices${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} tablets${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} Mac, Windows and Linux${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} camera or webcam requirements${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} playing without webcam${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} physical cards${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} private games${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} room links${copy.faqQuestionSuffix}`,
    `${copy.faqQuestionPrefix} starting requirements${copy.faqQuestionSuffix}`,
  ];
}

function getRouteSpecificSections(routeKey: SeoRouteKey, locale: LocaleCode): readonly LandingSectionContent[] {
  if (routeKey === 'home') {
    return [
      {
        id: 'public-faq',
        title: ROUTE_LABELS.faq[locale],
        body: [
          `${LOCALE_COPY[locale].faqIntro} ${LOCALE_COPY[locale].internalLinksIntro}`,
        ],
        links: [
          { label: ROUTE_LABELS.faq[locale], href: getSeoPath('faq', locale) },
        ],
      },
    ];
  }

  if (routeKey === 'faq') {
    return [
      {
        id: 'faq-categories',
        title: LOCALE_COPY[locale].useCasesTitle,
        body: [
          'CommanderZone, Commander online, deck import, deck builder, Asistente de mesa, platform comparisons, devices and privacy.',
        ],
      },
    ];
  }

  if (routeKey === 'tableAssistant' && locale === 'es') {
    return [
      {
        id: 'asistente-de-mesa',
        title: 'Asistente de mesa para partidas fisicas de Magic',
        body: [
          'El Asistente de mesa funciona como contador de vidas Magic, contador de vidas Commander y marcador de vidas para grupos que juegan en mesa fisica.',
          'Puedes usar el móvil como contador o una tablet como marcador visible, incluyendo seguimiento de daño de comandante sin automatizar reglas completas.',
        ],
      },
    ];
  }

  if (routeKey === 'waysToPlayCommanderOnline') {
    return [
      {
        id: 'comparison-options',
        title: 'Commander online options',
        body: [
          'SpellTable, Cockatrice, MTGO, MTG Arena, Untap.in and EDHPlay solve different ways to play Magic online.',
          'CommanderZone is positioned as a manual Commander table for groups that want shared state, links and flexible play without full rules enforcement.',
        ],
      },
    ];
  }

  return [];
}

const PUBLIC_FAQ_QUESTIONS: Readonly<Record<LocaleCode, readonly string[]>> = {
  es: [
    '¿Qué es CommanderZone?',
    '¿Cómo puedo jugar Commander online con amigos?',
    '¿Puedo jugar Magic: The Gathering online en CommanderZone?',
    '¿Necesito descargar algo para jugar?',
    '¿CommanderZone funciona desde navegador?',
    '¿Puedo crear una sala privada para jugar Commander?',
    '¿Cómo invito a mis amigos a una partida?',
    '¿Puedo jugar Commander online gratis?',
    '¿Necesito registrarme para crear una sala?',
    '¿CommanderZone está pensado para Commander multijugador?',
    '¿Puedo importar mi mazo de Commander?',
    '¿Puedo pegar una decklist para jugar online?',
    '¿CommanderZone tiene deck builder?',
    '¿Puedo crear un mazo de Commander desde cero?',
    '¿Puedo editar mi mazo antes de jugar?',
    '¿Puedo importar mazos desde Moxfield, Archidekt u otras plataformas?',
    '¿Qué formatos de decklist acepta CommanderZone?',
    '¿Puedo jugar online con un mazo que ya tengo creado?',
    '¿Qué es el Asistente de mesa?',
    '¿Puedo usar CommanderZone como asistente de mesa en una partida física?',
    '¿Puedo usar el móvil como contador de vidas de Magic?',
    '¿Puedo usar una tablet como asistente de mesa para Commander?',
    '¿El Asistente de mesa funciona para partidas presenciales?',
    '¿Puedo controlar el daño de comandante?',
    '¿Puedo contar vidas de varios jugadores?',
    '¿Puedo controlar veneno o infect?',
    '¿Necesito crear una sala online para usar el Asistente de mesa?',
    '¿CommanderZone es una alternativa a SpellTable?',
    '¿CommanderZone es una alternativa a Cockatrice?',
    '¿CommanderZone es una alternativa a MTGO?',
    '¿CommanderZone es una alternativa a MTG Arena?',
    '¿CommanderZone es una alternativa a Untap.in?',
    '¿CommanderZone es una alternativa a EDHPlay?',
    '¿Qué diferencia a CommanderZone de otras plataformas para jugar Commander online?',
    '¿CommanderZone funciona en móvil?',
    '¿CommanderZone funciona en tablet?',
    '¿CommanderZone funciona en Mac, Windows y Linux?',
    '¿Necesito cámara o webcam?',
    '¿Puedo jugar sin webcam?',
    '¿Puedo jugar con cartas físicas?',
    '¿Mis partidas son privadas?',
    '¿Puedo compartir una sala con un enlace?',
    '¿Qué necesito para empezar a jugar?',
  ],
  en: [
    'What is CommanderZone?',
    'How can I play Commander online with friends?',
    'Can I play Magic: The Gathering online on CommanderZone?',
    'Do I need to download anything to play?',
    'Does CommanderZone work in the browser?',
    'Can I create a private room to play Commander?',
    'How do I invite friends to a game?',
    'Can I play Commander online for free?',
    'Do I need an account to create a room?',
    'Is CommanderZone built for multiplayer Commander?',
    'Can I import my Commander deck?',
    'Can I paste a decklist to play online?',
    'Does CommanderZone include a deck builder?',
    'Can I create a Commander deck from scratch?',
    'Can I edit my deck before playing?',
    'Can I import decks from Moxfield, Archidekt or other platforms?',
    'Which decklist formats does CommanderZone accept?',
    'Can I play online with a deck I already created?',
    'What is the table assistant?',
    'Can I use CommanderZone as a table assistant in a physical game?',
    'Can I use my phone as a Magic life counter?',
    'Can I use a tablet as a Commander table assistant?',
    'Does the table assistant work for in-person games?',
    'Can I track commander damage?',
    'Can I track life totals for several players?',
    'Can I track poison or infect?',
    'Do I need to create an online room to use the table assistant?',
    'Is CommanderZone an alternative to SpellTable?',
    'Is CommanderZone an alternative to Cockatrice?',
    'Is CommanderZone an alternative to MTGO?',
    'Is CommanderZone an alternative to MTG Arena?',
    'Is CommanderZone an alternative to Untap.in?',
    'Is CommanderZone an alternative to EDHPlay?',
    'What makes CommanderZone different from other ways to play Commander online?',
    'Does CommanderZone work on mobile?',
    'Does CommanderZone work on tablets?',
    'Does CommanderZone work on Mac, Windows and Linux?',
    'Do I need a camera or webcam?',
    'Can I play without a webcam?',
    'Can I play with physical cards?',
    'Are my games private?',
    'Can I share a room with a link?',
    'What do I need to start playing?',
  ],
  de: [],
  fr: [],
  it: [],
  pt: [],
  ja: [],
  ko: [],
  'zh-hans': [],
  'zh-hant': [],
  nl: [],
  ca: [],
  ru: [],
};

function getRelatedRouteKeys(routeKey: SeoRouteKey): readonly SeoRouteKey[] {
  const routes: readonly SeoRouteKey[] = [
    'playCommanderOnline',
    'createCommanderRoom',
    'importCommanderDeck',
    'commanderDeckBuilder',
    'tableAssistant',
    'waysToPlayCommanderOnline',
    'howToPlayCommanderOnline',
    'faq',
  ];

  return routes.filter((relatedRouteKey) => relatedRouteKey !== routeKey).slice(0, 4);
}

function getOpenGraphImagePath(routeKey: SeoRouteKey): string {
  const images: Partial<Record<SeoRouteKey, string>> = {
    home: '/assets/og/home-og.png',
    playCommanderOnline: '/assets/og/play-commander-og.png',
    tableAssistant: '/assets/og/table-assistant-og.png',
  };

  return images[routeKey] ?? '/assets/og/default-og.png';
}
