name: Validate Go Runtime

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: go-runtime-ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  runtime:
    name: go-runtime
    uses: ./.github/workflows/go-runtime-ci-reusable.yml
